// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aegis/v2/agent.proto

package aegisv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_aegis_v2_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v2_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterAgentRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_aegis_v2_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v2_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterAgentResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type UpdateAgentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // IDLE, UPLOADING, UPDATING_CONFIG, ERROR, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentStatusRequest) Reset() {
	*x = UpdateAgentStatusRequest{}
	mi := &file_aegis_v2_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentStatusRequest) ProtoMessage() {}

func (x *UpdateAgentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateAgentStatusRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v2_agent_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateAgentStatusRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UpdateAgentStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateAgentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentStatusResponse) Reset() {
	*x = UpdateAgentStatusResponse{}
	mi := &file_aegis_v2_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentStatusResponse) ProtoMessage() {}

func (x *UpdateAgentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateAgentStatusResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v2_agent_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateAgentStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetUploadLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadLinkRequest) Reset() {
	*x = GetUploadLinkRequest{}
	mi := &file_aegis_v2_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadLinkRequest) ProtoMessage() {}

func (x *GetUploadLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadLinkRequest.ProtoReflect.Descriptor instead.
func (*GetUploadLinkRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v2_agent_proto_rawDescGZIP(), []int{4}
}

func (x *GetUploadLinkRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetUploadLinkRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *GetUploadLinkRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type GetUploadLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadLinkResponse) Reset() {
	*x = GetUploadLinkResponse{}
	mi := &file_aegis_v2_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadLinkResponse) ProtoMessage() {}

func (x *GetUploadLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadLinkResponse.ProtoReflect.Descriptor instead.
func (*GetUploadLinkResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v2_agent_proto_rawDescGZIP(), []int{5}
}

func (x *GetUploadLinkResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetUploadLinkResponse) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

var File_aegis_v2_agent_proto protoreflect.FileDescriptor

const file_aegis_v2_agent_proto_rawDesc = "" +
	"\n" +
	"\x14aegis/v2/agent.proto\x12\baegis.v2\x1a\x1fgoogle/protobuf/timestamp.proto\"@\n" +
	"\x14RegisterAgentRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"2\n" +
	"\x15RegisterAgentResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"M\n" +
	"\x18UpdateAgentStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"5\n" +
	"\x19UpdateAgentStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"p\n" +
	"\x14GetUploadLinkRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"A\n" +
	"\x15GetUploadLinkResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method2\x90\x02\n" +
	"\fAgentService\x12P\n" +
	"\rRegisterAgent\x12\x1e.aegis.v2.RegisterAgentRequest\x1a\x1f.aegis.v2.RegisterAgentResponse\x12\\\n" +
	"\x11UpdateAgentStatus\x12\".aegis.v2.UpdateAgentStatusRequest\x1a#.aegis.v2.UpdateAgentStatusResponse\x12P\n" +
	"\rGetUploadLink\x12\x1e.aegis.v2.GetUploadLinkRequest\x1a\x1f.aegis.v2.GetUploadLinkResponseBJZHgithub.com/Aegis-AI-Organizations/Aegis-AI-Proto/gen/go/aegis/v2;aegisv2b\x06proto3"

var (
	file_aegis_v2_agent_proto_rawDescOnce sync.Once
	file_aegis_v2_agent_proto_rawDescData []byte
)

func file_aegis_v2_agent_proto_rawDescGZIP() []byte {
	file_aegis_v2_agent_proto_rawDescOnce.Do(func() {
		file_aegis_v2_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aegis_v2_agent_proto_rawDesc), len(file_aegis_v2_agent_proto_rawDesc)))
	})
	return file_aegis_v2_agent_proto_rawDescData
}

var file_aegis_v2_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_aegis_v2_agent_proto_goTypes = []any{
	(*RegisterAgentRequest)(nil),      // 0: aegis.v2.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),     // 1: aegis.v2.RegisterAgentResponse
	(*UpdateAgentStatusRequest)(nil),  // 2: aegis.v2.UpdateAgentStatusRequest
	(*UpdateAgentStatusResponse)(nil), // 3: aegis.v2.UpdateAgentStatusResponse
	(*GetUploadLinkRequest)(nil),      // 4: aegis.v2.GetUploadLinkRequest
	(*GetUploadLinkResponse)(nil),     // 5: aegis.v2.GetUploadLinkResponse
}
var file_aegis_v2_agent_proto_depIdxs = []int32{
	0, // 0: aegis.v2.AgentService.RegisterAgent:input_type -> aegis.v2.RegisterAgentRequest
	2, // 1: aegis.v2.AgentService.UpdateAgentStatus:input_type -> aegis.v2.UpdateAgentStatusRequest
	4, // 2: aegis.v2.AgentService.GetUploadLink:input_type -> aegis.v2.GetUploadLinkRequest
	1, // 3: aegis.v2.AgentService.RegisterAgent:output_type -> aegis.v2.RegisterAgentResponse
	3, // 4: aegis.v2.AgentService.UpdateAgentStatus:output_type -> aegis.v2.UpdateAgentStatusResponse
	5, // 5: aegis.v2.AgentService.GetUploadLink:output_type -> aegis.v2.GetUploadLinkResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aegis_v2_agent_proto_init() }
func file_aegis_v2_agent_proto_init() {
	if File_aegis_v2_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aegis_v2_agent_proto_rawDesc), len(file_aegis_v2_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aegis_v2_agent_proto_goTypes,
		DependencyIndexes: file_aegis_v2_agent_proto_depIdxs,
		MessageInfos:      file_aegis_v2_agent_proto_msgTypes,
	}.Build()
	File_aegis_v2_agent_proto = out.File
	file_aegis_v2_agent_proto_goTypes = nil
	file_aegis_v2_agent_proto_depIdxs = nil
}
