// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aegis/v2/company.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrganizationSize int32

const (
	OrganizationSize_ORGANIZATION_SIZE_UNSPECIFIED OrganizationSize = 0
	OrganizationSize_ORGANIZATION_SIZE_1           OrganizationSize = 1
	OrganizationSize_ORGANIZATION_SIZE_2_10        OrganizationSize = 2
	OrganizationSize_ORGANIZATION_SIZE_11_50       OrganizationSize = 3
	OrganizationSize_ORGANIZATION_SIZE_51_200      OrganizationSize = 4
	OrganizationSize_ORGANIZATION_SIZE_201_500     OrganizationSize = 5
	OrganizationSize_ORGANIZATION_SIZE_501_1000    OrganizationSize = 6
	OrganizationSize_ORGANIZATION_SIZE_1001_5000   OrganizationSize = 7
	OrganizationSize_ORGANIZATION_SIZE_5001_10000  OrganizationSize = 8
	OrganizationSize_ORGANIZATION_SIZE_10001_PLUS  OrganizationSize = 9
)

// Enum value maps for OrganizationSize.
var (
	OrganizationSize_name = map[int32]string{
		0: "ORGANIZATION_SIZE_UNSPECIFIED",
		1: "ORGANIZATION_SIZE_1",
		2: "ORGANIZATION_SIZE_2_10",
		3: "ORGANIZATION_SIZE_11_50",
		4: "ORGANIZATION_SIZE_51_200",
		5: "ORGANIZATION_SIZE_201_500",
		6: "ORGANIZATION_SIZE_501_1000",
		7: "ORGANIZATION_SIZE_1001_5000",
		8: "ORGANIZATION_SIZE_5001_10000",
		9: "ORGANIZATION_SIZE_10001_PLUS",
	}
	OrganizationSize_value = map[string]int32{
		"ORGANIZATION_SIZE_UNSPECIFIED": 0,
		"ORGANIZATION_SIZE_1":           1,
		"ORGANIZATION_SIZE_2_10":        2,
		"ORGANIZATION_SIZE_11_50":       3,
		"ORGANIZATION_SIZE_51_200":      4,
		"ORGANIZATION_SIZE_201_500":     5,
		"ORGANIZATION_SIZE_501_1000":    6,
		"ORGANIZATION_SIZE_1001_5000":   7,
		"ORGANIZATION_SIZE_5001_10000":  8,
		"ORGANIZATION_SIZE_10001_PLUS":  9,
	}
)

func (x OrganizationSize) Enum() *OrganizationSize {
	p := new(OrganizationSize)
	*p = x
	return p
}

func (x OrganizationSize) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrganizationSize) Descriptor() protoreflect.EnumDescriptor {
	return file_aegis_v2_company_proto_enumTypes[0].Descriptor()
}

func (OrganizationSize) Type() protoreflect.EnumType {
	return &file_aegis_v2_company_proto_enumTypes[0]
}

func (x OrganizationSize) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrganizationSize.Descriptor instead.
func (OrganizationSize) EnumDescriptor() ([]byte, []int) {
	return file_aegis_v2_company_proto_rawDescGZIP(), []int{0}
}

type OrganizationType int32

const (
	OrganizationType_ORGANIZATION_TYPE_UNSPECIFIED                OrganizationType = 0
	OrganizationType_ORGANIZATION_TYPE_IT_SERVICES_AND_CONSULTING OrganizationType = 1
	OrganizationType_ORGANIZATION_TYPE_SOFTWARE_DEVELOPMENT       OrganizationType = 2
	OrganizationType_ORGANIZATION_TYPE_FINANCIAL_SERVICES         OrganizationType = 3
	OrganizationType_ORGANIZATION_TYPE_HOSPITALS_AND_HEALTH_CARE  OrganizationType = 4
	OrganizationType_ORGANIZATION_TYPE_RETAIL                     OrganizationType = 5
	OrganizationType_ORGANIZATION_TYPE_GOVERNMENT_ADMINISTRATION  OrganizationType = 6
	OrganizationType_ORGANIZATION_TYPE_MANUFACTURING              OrganizationType = 7
	OrganizationType_ORGANIZATION_TYPE_OTHER                      OrganizationType = 8
)

// Enum value maps for OrganizationType.
var (
	OrganizationType_name = map[int32]string{
		0: "ORGANIZATION_TYPE_UNSPECIFIED",
		1: "ORGANIZATION_TYPE_IT_SERVICES_AND_CONSULTING",
		2: "ORGANIZATION_TYPE_SOFTWARE_DEVELOPMENT",
		3: "ORGANIZATION_TYPE_FINANCIAL_SERVICES",
		4: "ORGANIZATION_TYPE_HOSPITALS_AND_HEALTH_CARE",
		5: "ORGANIZATION_TYPE_RETAIL",
		6: "ORGANIZATION_TYPE_GOVERNMENT_ADMINISTRATION",
		7: "ORGANIZATION_TYPE_MANUFACTURING",
		8: "ORGANIZATION_TYPE_OTHER",
	}
	OrganizationType_value = map[string]int32{
		"ORGANIZATION_TYPE_UNSPECIFIED":                0,
		"ORGANIZATION_TYPE_IT_SERVICES_AND_CONSULTING": 1,
		"ORGANIZATION_TYPE_SOFTWARE_DEVELOPMENT":       2,
		"ORGANIZATION_TYPE_FINANCIAL_SERVICES":         3,
		"ORGANIZATION_TYPE_HOSPITALS_AND_HEALTH_CARE":  4,
		"ORGANIZATION_TYPE_RETAIL":                     5,
		"ORGANIZATION_TYPE_GOVERNMENT_ADMINISTRATION":  6,
		"ORGANIZATION_TYPE_MANUFACTURING":              7,
		"ORGANIZATION_TYPE_OTHER":                      8,
	}
)

func (x OrganizationType) Enum() *OrganizationType {
	p := new(OrganizationType)
	*p = x
	return p
}

func (x OrganizationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrganizationType) Descriptor() protoreflect.EnumDescriptor {
	return file_aegis_v2_company_proto_enumTypes[1].Descriptor()
}

func (OrganizationType) Type() protoreflect.EnumType {
	return &file_aegis_v2_company_proto_enumTypes[1]
}

func (x OrganizationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrganizationType.Descriptor instead.
func (OrganizationType) EnumDescriptor() ([]byte, []int) {
	return file_aegis_v2_company_proto_rawDescGZIP(), []int{1}
}

type ListAuditLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	CompanyId     string                 `protobuf:"bytes,3,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"` // Optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditLogsRequest) Reset() {
	*x = ListAuditLogsRequest{}
	mi := &file_aegis_v2_company_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditLogsRequest) ProtoMessage() {}

func (x *ListAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_company_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*ListAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v2_company_proto_rawDescGZIP(), []int{0}
}

func (x *ListAuditLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAuditLogsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListAuditLogsRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type ListAuditLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*AuditLogEntry       `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditLogsResponse) Reset() {
	*x = ListAuditLogsResponse{}
	mi := &file_aegis_v2_company_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditLogsResponse) ProtoMessage() {}

func (x *ListAuditLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_company_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditLogsResponse.ProtoReflect.Descriptor instead.
func (*ListAuditLogsResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v2_company_proto_rawDescGZIP(), []int{1}
}

func (x *ListAuditLogsResponse) GetLogs() []*AuditLogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *ListAuditLogsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AuditLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,3,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	TargetType    string                 `protobuf:"bytes,5,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId      string                 `protobuf:"bytes,6,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Details       string                 `protobuf:"bytes,7,opt,name=details,proto3" json:"details,omitempty"` // JSON string
	IpAddress     string                 `protobuf:"bytes,8,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogEntry) Reset() {
	*x = AuditLogEntry{}
	mi := &file_aegis_v2_company_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogEntry) ProtoMessage() {}

func (x *AuditLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_company_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogEntry.ProtoReflect.Descriptor instead.
func (*AuditLogEntry) Descriptor() ([]byte, []int) {
	return file_aegis_v2_company_proto_rawDescGZIP(), []int{2}
}

func (x *AuditLogEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditLogEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuditLogEntry) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *AuditLogEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditLogEntry) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *AuditLogEntry) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *AuditLogEntry) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *AuditLogEntry) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AuditLogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type WatchCompanyUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchCompanyUpdatesRequest) Reset() {
	*x = WatchCompanyUpdatesRequest{}
	mi := &file_aegis_v2_company_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchCompanyUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchCompanyUpdatesRequest) ProtoMessage() {}

func (x *WatchCompanyUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_company_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchCompanyUpdatesRequest.ProtoReflect.Descriptor instead.
func (*WatchCompanyUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v2_company_proto_rawDescGZIP(), []int{3}
}

type WatchCompanyUpdatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "COMPANY_CREATED", "USER_CREATED", etc.
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityName    string                 `protobuf:"bytes,3,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchCompanyUpdatesResponse) Reset() {
	*x = WatchCompanyUpdatesResponse{}
	mi := &file_aegis_v2_company_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchCompanyUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchCompanyUpdatesResponse) ProtoMessage() {}

func (x *WatchCompanyUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_company_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchCompanyUpdatesResponse.ProtoReflect.Descriptor instead.
func (*WatchCompanyUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v2_company_proto_rawDescGZIP(), []int{4}
}

func (x *WatchCompanyUpdatesResponse) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *WatchCompanyUpdatesResponse) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *WatchCompanyUpdatesResponse) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

type CreateCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OwnerEmail    string                 `protobuf:"bytes,2,opt,name=owner_email,json=ownerEmail,proto3" json:"owner_email,omitempty"` // Email of the user who will own this company
	OrgSize       OrganizationSize       `protobuf:"varint,3,opt,name=org_size,json=orgSize,proto3,enum=aegis.v2.OrganizationSize" json:"org_size,omitempty"`
	OrgType       OrganizationType       `protobuf:"varint,4,opt,name=org_type,json=orgType,proto3,enum=aegis.v2.OrganizationType" json:"org_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCompanyRequest) Reset() {
	*x = CreateCompanyRequest{}
	mi := &file_aegis_v2_company_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompanyRequest) ProtoMessage() {}

func (x *CreateCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_company_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompanyRequest.ProtoReflect.Descriptor instead.
func (*CreateCompanyRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v2_company_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCompanyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCompanyRequest) GetOwnerEmail() string {
	if x != nil {
		return x.OwnerEmail
	}
	return ""
}

func (x *CreateCompanyRequest) GetOrgSize() OrganizationSize {
	if x != nil {
		return x.OrgSize
	}
	return OrganizationSize_ORGANIZATION_SIZE_UNSPECIFIED
}

func (x *CreateCompanyRequest) GetOrgType() OrganizationType {
	if x != nil {
		return x.OrgType
	}
	return OrganizationType_ORGANIZATION_TYPE_UNSPECIFIED
}

type CreateCompanyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCompanyResponse) Reset() {
	*x = CreateCompanyResponse{}
	mi := &file_aegis_v2_company_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompanyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompanyResponse) ProtoMessage() {}

func (x *CreateCompanyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_company_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompanyResponse.ProtoReflect.Descriptor instead.
func (*CreateCompanyResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v2_company_proto_rawDescGZIP(), []int{6}
}

func (x *CreateCompanyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateCompanyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type OnboardCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyName   string                 `protobuf:"bytes,1,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	OwnerName     string                 `protobuf:"bytes,2,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	OwnerEmail    string                 `protobuf:"bytes,3,opt,name=owner_email,json=ownerEmail,proto3" json:"owner_email,omitempty"`
	OwnerPassword string                 `protobuf:"bytes,4,opt,name=owner_password,json=ownerPassword,proto3" json:"owner_password,omitempty"`
	OrgSize       OrganizationSize       `protobuf:"varint,5,opt,name=org_size,json=orgSize,proto3,enum=aegis.v2.OrganizationSize" json:"org_size,omitempty"`
	OrgType       OrganizationType       `protobuf:"varint,6,opt,name=org_type,json=orgType,proto3,enum=aegis.v2.OrganizationType" json:"org_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnboardCompanyRequest) Reset() {
	*x = OnboardCompanyRequest{}
	mi := &file_aegis_v2_company_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnboardCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnboardCompanyRequest) ProtoMessage() {}

func (x *OnboardCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_company_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnboardCompanyRequest.ProtoReflect.Descriptor instead.
func (*OnboardCompanyRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v2_company_proto_rawDescGZIP(), []int{7}
}

func (x *OnboardCompanyRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *OnboardCompanyRequest) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *OnboardCompanyRequest) GetOwnerEmail() string {
	if x != nil {
		return x.OwnerEmail
	}
	return ""
}

func (x *OnboardCompanyRequest) GetOwnerPassword() string {
	if x != nil {
		return x.OwnerPassword
	}
	return ""
}

func (x *OnboardCompanyRequest) GetOrgSize() OrganizationSize {
	if x != nil {
		return x.OrgSize
	}
	return OrganizationSize_ORGANIZATION_SIZE_UNSPECIFIED
}

func (x *OnboardCompanyRequest) GetOrgType() OrganizationType {
	if x != nil {
		return x.OrgType
	}
	return OrganizationType_ORGANIZATION_TYPE_UNSPECIFIED
}

type OnboardCompanyResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CompanyId       string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	OwnerId         string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	DeploymentToken string                 `protobuf:"bytes,3,opt,name=deployment_token,json=deploymentToken,proto3" json:"deployment_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OnboardCompanyResponse) Reset() {
	*x = OnboardCompanyResponse{}
	mi := &file_aegis_v2_company_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnboardCompanyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnboardCompanyResponse) ProtoMessage() {}

func (x *OnboardCompanyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_company_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnboardCompanyResponse.ProtoReflect.Descriptor instead.
func (*OnboardCompanyResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v2_company_proto_rawDescGZIP(), []int{8}
}

func (x *OnboardCompanyResponse) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *OnboardCompanyResponse) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *OnboardCompanyResponse) GetDeploymentToken() string {
	if x != nil {
		return x.DeploymentToken
	}
	return ""
}

type RotateAgentTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateAgentTokenRequest) Reset() {
	*x = RotateAgentTokenRequest{}
	mi := &file_aegis_v2_company_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateAgentTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateAgentTokenRequest) ProtoMessage() {}

func (x *RotateAgentTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_company_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateAgentTokenRequest.ProtoReflect.Descriptor instead.
func (*RotateAgentTokenRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v2_company_proto_rawDescGZIP(), []int{9}
}

func (x *RotateAgentTokenRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type RotateAgentTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentToken    string                 `protobuf:"bytes,1,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateAgentTokenResponse) Reset() {
	*x = RotateAgentTokenResponse{}
	mi := &file_aegis_v2_company_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateAgentTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateAgentTokenResponse) ProtoMessage() {}

func (x *RotateAgentTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_company_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateAgentTokenResponse.ProtoReflect.Descriptor instead.
func (*RotateAgentTokenResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v2_company_proto_rawDescGZIP(), []int{10}
}

func (x *RotateAgentTokenResponse) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

type RevokeAgentTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAgentTokenRequest) Reset() {
	*x = RevokeAgentTokenRequest{}
	mi := &file_aegis_v2_company_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAgentTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAgentTokenRequest) ProtoMessage() {}

func (x *RevokeAgentTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_company_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAgentTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeAgentTokenRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v2_company_proto_rawDescGZIP(), []int{11}
}

func (x *RevokeAgentTokenRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type RevokeAgentTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAgentTokenResponse) Reset() {
	*x = RevokeAgentTokenResponse{}
	mi := &file_aegis_v2_company_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAgentTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAgentTokenResponse) ProtoMessage() {}

func (x *RevokeAgentTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_company_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAgentTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeAgentTokenResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v2_company_proto_rawDescGZIP(), []int{12}
}

func (x *RevokeAgentTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListCompaniesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCompaniesRequest) Reset() {
	*x = ListCompaniesRequest{}
	mi := &file_aegis_v2_company_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCompaniesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCompaniesRequest) ProtoMessage() {}

func (x *ListCompaniesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_company_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCompaniesRequest.ProtoReflect.Descriptor instead.
func (*ListCompaniesRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v2_company_proto_rawDescGZIP(), []int{13}
}

type ListCompaniesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Companies     []*CompanySummary      `protobuf:"bytes,1,rep,name=companies,proto3" json:"companies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCompaniesResponse) Reset() {
	*x = ListCompaniesResponse{}
	mi := &file_aegis_v2_company_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCompaniesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCompaniesResponse) ProtoMessage() {}

func (x *ListCompaniesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_company_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCompaniesResponse.ProtoReflect.Descriptor instead.
func (*ListCompaniesResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v2_company_proto_rawDescGZIP(), []int{14}
}

func (x *ListCompaniesResponse) GetCompanies() []*CompanySummary {
	if x != nil {
		return x.Companies
	}
	return nil
}

type CompanySummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId         string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OwnerEmail      string                 `protobuf:"bytes,4,opt,name=owner_email,json=ownerEmail,proto3" json:"owner_email,omitempty"`
	MemberCount     int32                  `protobuf:"varint,5,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	DeploymentToken string                 `protobuf:"bytes,6,opt,name=deployment_token,json=deploymentToken,proto3" json:"deployment_token,omitempty"`
	AvatarUrl       string                 `protobuf:"bytes,7,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	OrgSize         OrganizationSize       `protobuf:"varint,8,opt,name=org_size,json=orgSize,proto3,enum=aegis.v2.OrganizationSize" json:"org_size,omitempty"`
	OrgType         OrganizationType       `protobuf:"varint,9,opt,name=org_type,json=orgType,proto3,enum=aegis.v2.OrganizationType" json:"org_type,omitempty"`
	TokenBalance    int64                  `protobuf:"varint,10,opt,name=token_balance,json=tokenBalance,proto3" json:"token_balance,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompanySummary) Reset() {
	*x = CompanySummary{}
	mi := &file_aegis_v2_company_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanySummary) ProtoMessage() {}

func (x *CompanySummary) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_company_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanySummary.ProtoReflect.Descriptor instead.
func (*CompanySummary) Descriptor() ([]byte, []int) {
	return file_aegis_v2_company_proto_rawDescGZIP(), []int{15}
}

func (x *CompanySummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompanySummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompanySummary) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CompanySummary) GetOwnerEmail() string {
	if x != nil {
		return x.OwnerEmail
	}
	return ""
}

func (x *CompanySummary) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *CompanySummary) GetDeploymentToken() string {
	if x != nil {
		return x.DeploymentToken
	}
	return ""
}

func (x *CompanySummary) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *CompanySummary) GetOrgSize() OrganizationSize {
	if x != nil {
		return x.OrgSize
	}
	return OrganizationSize_ORGANIZATION_SIZE_UNSPECIFIED
}

func (x *CompanySummary) GetOrgType() OrganizationType {
	if x != nil {
		return x.OrgType
	}
	return OrganizationType_ORGANIZATION_TYPE_UNSPECIFIED
}

func (x *CompanySummary) GetTokenBalance() int64 {
	if x != nil {
		return x.TokenBalance
	}
	return 0
}

var File_aegis_v2_company_proto protoreflect.FileDescriptor

const file_aegis_v2_company_proto_rawDesc = "" +
	"\n" +
	"\x16aegis/v2/company.proto\x12\baegis.v2\x1a\x1fgoogle/protobuf/timestamp.proto\"c\n" +
	"\x14ListAuditLogsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x1d\n" +
	"\n" +
	"company_id\x18\x03 \x01(\tR\tcompanyId\"Z\n" +
	"\x15ListAuditLogsResponse\x12+\n" +
	"\x04logs\x18\x01 \x03(\v2\x17.aegis.v2.AuditLogEntryR\x04logs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xa0\x02\n" +
	"\rAuditLogEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x03 \x01(\tR\tcompanyId\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1f\n" +
	"\vtarget_type\x18\x05 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x06 \x01(\tR\btargetId\x12\x18\n" +
	"\adetails\x18\a \x01(\tR\adetails\x12\x1d\n" +
	"\n" +
	"ip_address\x18\b \x01(\tR\tipAddress\x128\n" +
	"\ttimestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x1c\n" +
	"\x1aWatchCompanyUpdatesRequest\"z\n" +
	"\x1bWatchCompanyUpdatesResponse\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x1f\n" +
	"\ventity_name\x18\x03 \x01(\tR\n" +
	"entityName\"\xb9\x01\n" +
	"\x14CreateCompanyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vowner_email\x18\x02 \x01(\tR\n" +
	"ownerEmail\x125\n" +
	"\borg_size\x18\x03 \x01(\x0e2\x1a.aegis.v2.OrganizationSizeR\aorgSize\x125\n" +
	"\borg_type\x18\x04 \x01(\x0e2\x1a.aegis.v2.OrganizationTypeR\aorgType\";\n" +
	"\x15CreateCompanyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8f\x02\n" +
	"\x15OnboardCompanyRequest\x12!\n" +
	"\fcompany_name\x18\x01 \x01(\tR\vcompanyName\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x02 \x01(\tR\townerName\x12\x1f\n" +
	"\vowner_email\x18\x03 \x01(\tR\n" +
	"ownerEmail\x12%\n" +
	"\x0eowner_password\x18\x04 \x01(\tR\rownerPassword\x125\n" +
	"\borg_size\x18\x05 \x01(\x0e2\x1a.aegis.v2.OrganizationSizeR\aorgSize\x125\n" +
	"\borg_type\x18\x06 \x01(\x0e2\x1a.aegis.v2.OrganizationTypeR\aorgType\"}\n" +
	"\x16OnboardCompanyResponse\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12)\n" +
	"\x10deployment_token\x18\x03 \x01(\tR\x0fdeploymentToken\"8\n" +
	"\x17RotateAgentTokenRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\";\n" +
	"\x18RotateAgentTokenResponse\x12\x1f\n" +
	"\vagent_token\x18\x01 \x01(\tR\n" +
	"agentToken\"8\n" +
	"\x17RevokeAgentTokenRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\"4\n" +
	"\x18RevokeAgentTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x16\n" +
	"\x14ListCompaniesRequest\"O\n" +
	"\x15ListCompaniesResponse\x126\n" +
	"\tcompanies\x18\x01 \x03(\v2\x18.aegis.v2.CompanySummaryR\tcompanies\"\xf0\x02\n" +
	"\x0eCompanySummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x1f\n" +
	"\vowner_email\x18\x04 \x01(\tR\n" +
	"ownerEmail\x12!\n" +
	"\fmember_count\x18\x05 \x01(\x05R\vmemberCount\x12)\n" +
	"\x10deployment_token\x18\x06 \x01(\tR\x0fdeploymentToken\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\a \x01(\tR\tavatarUrl\x125\n" +
	"\borg_size\x18\b \x01(\x0e2\x1a.aegis.v2.OrganizationSizeR\aorgSize\x125\n" +
	"\borg_type\x18\t \x01(\x0e2\x1a.aegis.v2.OrganizationTypeR\aorgType\x12#\n" +
	"\rtoken_balance\x18\n" +
	" \x01(\x03R\ftokenBalance*\xc9\x02\n" +
	"\x10OrganizationSize\x12!\n" +
	"\x1dORGANIZATION_SIZE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ORGANIZATION_SIZE_1\x10\x01\x12\x1a\n" +
	"\x16ORGANIZATION_SIZE_2_10\x10\x02\x12\x1b\n" +
	"\x17ORGANIZATION_SIZE_11_50\x10\x03\x12\x1c\n" +
	"\x18ORGANIZATION_SIZE_51_200\x10\x04\x12\x1d\n" +
	"\x19ORGANIZATION_SIZE_201_500\x10\x05\x12\x1e\n" +
	"\x1aORGANIZATION_SIZE_501_1000\x10\x06\x12\x1f\n" +
	"\x1bORGANIZATION_SIZE_1001_5000\x10\a\x12 \n" +
	"\x1cORGANIZATION_SIZE_5001_10000\x10\b\x12 \n" +
	"\x1cORGANIZATION_SIZE_10001_PLUS\x10\t*\xff\x02\n" +
	"\x10OrganizationType\x12!\n" +
	"\x1dORGANIZATION_TYPE_UNSPECIFIED\x10\x00\x120\n" +
	",ORGANIZATION_TYPE_IT_SERVICES_AND_CONSULTING\x10\x01\x12*\n" +
	"&ORGANIZATION_TYPE_SOFTWARE_DEVELOPMENT\x10\x02\x12(\n" +
	"$ORGANIZATION_TYPE_FINANCIAL_SERVICES\x10\x03\x12/\n" +
	"+ORGANIZATION_TYPE_HOSPITALS_AND_HEALTH_CARE\x10\x04\x12\x1c\n" +
	"\x18ORGANIZATION_TYPE_RETAIL\x10\x05\x12/\n" +
	"+ORGANIZATION_TYPE_GOVERNMENT_ADMINISTRATION\x10\x06\x12#\n" +
	"\x1fORGANIZATION_TYPE_MANUFACTURING\x10\a\x12\x1b\n" +
	"\x17ORGANIZATION_TYPE_OTHER\x10\b2\xf7\x04\n" +
	"\x0eCompanyService\x12P\n" +
	"\rCreateCompany\x12\x1e.aegis.v2.CreateCompanyRequest\x1a\x1f.aegis.v2.CreateCompanyResponse\x12P\n" +
	"\rListCompanies\x12\x1e.aegis.v2.ListCompaniesRequest\x1a\x1f.aegis.v2.ListCompaniesResponse\x12S\n" +
	"\x0eOnboardCompany\x12\x1f.aegis.v2.OnboardCompanyRequest\x1a .aegis.v2.OnboardCompanyResponse\x12Y\n" +
	"\x10RotateAgentToken\x12!.aegis.v2.RotateAgentTokenRequest\x1a\".aegis.v2.RotateAgentTokenResponse\x12Y\n" +
	"\x10RevokeAgentToken\x12!.aegis.v2.RevokeAgentTokenRequest\x1a\".aegis.v2.RevokeAgentTokenResponse\x12d\n" +
	"\x13WatchCompanyUpdates\x12$.aegis.v2.WatchCompanyUpdatesRequest\x1a%.aegis.v2.WatchCompanyUpdatesResponse0\x01\x12P\n" +
	"\rListAuditLogs\x12\x1e.aegis.v2.ListAuditLogsRequest\x1a\x1f.aegis.v2.ListAuditLogsResponseBPZNgithub.com/Aegis-AI-Organizations/aegis-ai-api-gateway/internal/agrpc/aegis/v2b\x06proto3"

var (
	file_aegis_v2_company_proto_rawDescOnce sync.Once
	file_aegis_v2_company_proto_rawDescData []byte
)

func file_aegis_v2_company_proto_rawDescGZIP() []byte {
	file_aegis_v2_company_proto_rawDescOnce.Do(func() {
		file_aegis_v2_company_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aegis_v2_company_proto_rawDesc), len(file_aegis_v2_company_proto_rawDesc)))
	})
	return file_aegis_v2_company_proto_rawDescData
}

var file_aegis_v2_company_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_aegis_v2_company_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_aegis_v2_company_proto_goTypes = []any{
	(OrganizationSize)(0),               // 0: aegis.v2.OrganizationSize
	(OrganizationType)(0),               // 1: aegis.v2.OrganizationType
	(*ListAuditLogsRequest)(nil),        // 2: aegis.v2.ListAuditLogsRequest
	(*ListAuditLogsResponse)(nil),       // 3: aegis.v2.ListAuditLogsResponse
	(*AuditLogEntry)(nil),               // 4: aegis.v2.AuditLogEntry
	(*WatchCompanyUpdatesRequest)(nil),  // 5: aegis.v2.WatchCompanyUpdatesRequest
	(*WatchCompanyUpdatesResponse)(nil), // 6: aegis.v2.WatchCompanyUpdatesResponse
	(*CreateCompanyRequest)(nil),        // 7: aegis.v2.CreateCompanyRequest
	(*CreateCompanyResponse)(nil),       // 8: aegis.v2.CreateCompanyResponse
	(*OnboardCompanyRequest)(nil),       // 9: aegis.v2.OnboardCompanyRequest
	(*OnboardCompanyResponse)(nil),      // 10: aegis.v2.OnboardCompanyResponse
	(*RotateAgentTokenRequest)(nil),     // 11: aegis.v2.RotateAgentTokenRequest
	(*RotateAgentTokenResponse)(nil),    // 12: aegis.v2.RotateAgentTokenResponse
	(*RevokeAgentTokenRequest)(nil),     // 13: aegis.v2.RevokeAgentTokenRequest
	(*RevokeAgentTokenResponse)(nil),    // 14: aegis.v2.RevokeAgentTokenResponse
	(*ListCompaniesRequest)(nil),        // 15: aegis.v2.ListCompaniesRequest
	(*ListCompaniesResponse)(nil),       // 16: aegis.v2.ListCompaniesResponse
	(*CompanySummary)(nil),              // 17: aegis.v2.CompanySummary
	(*timestamppb.Timestamp)(nil),       // 18: google.protobuf.Timestamp
}
var file_aegis_v2_company_proto_depIdxs = []int32{
	4,  // 0: aegis.v2.ListAuditLogsResponse.logs:type_name -> aegis.v2.AuditLogEntry
	18, // 1: aegis.v2.AuditLogEntry.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 2: aegis.v2.CreateCompanyRequest.org_size:type_name -> aegis.v2.OrganizationSize
	1,  // 3: aegis.v2.CreateCompanyRequest.org_type:type_name -> aegis.v2.OrganizationType
	0,  // 4: aegis.v2.OnboardCompanyRequest.org_size:type_name -> aegis.v2.OrganizationSize
	1,  // 5: aegis.v2.OnboardCompanyRequest.org_type:type_name -> aegis.v2.OrganizationType
	17, // 6: aegis.v2.ListCompaniesResponse.companies:type_name -> aegis.v2.CompanySummary
	0,  // 7: aegis.v2.CompanySummary.org_size:type_name -> aegis.v2.OrganizationSize
	1,  // 8: aegis.v2.CompanySummary.org_type:type_name -> aegis.v2.OrganizationType
	7,  // 9: aegis.v2.CompanyService.CreateCompany:input_type -> aegis.v2.CreateCompanyRequest
	15, // 10: aegis.v2.CompanyService.ListCompanies:input_type -> aegis.v2.ListCompaniesRequest
	9,  // 11: aegis.v2.CompanyService.OnboardCompany:input_type -> aegis.v2.OnboardCompanyRequest
	11, // 12: aegis.v2.CompanyService.RotateAgentToken:input_type -> aegis.v2.RotateAgentTokenRequest
	13, // 13: aegis.v2.CompanyService.RevokeAgentToken:input_type -> aegis.v2.RevokeAgentTokenRequest
	5,  // 14: aegis.v2.CompanyService.WatchCompanyUpdates:input_type -> aegis.v2.WatchCompanyUpdatesRequest
	2,  // 15: aegis.v2.CompanyService.ListAuditLogs:input_type -> aegis.v2.ListAuditLogsRequest
	8,  // 16: aegis.v2.CompanyService.CreateCompany:output_type -> aegis.v2.CreateCompanyResponse
	16, // 17: aegis.v2.CompanyService.ListCompanies:output_type -> aegis.v2.ListCompaniesResponse
	10, // 18: aegis.v2.CompanyService.OnboardCompany:output_type -> aegis.v2.OnboardCompanyResponse
	12, // 19: aegis.v2.CompanyService.RotateAgentToken:output_type -> aegis.v2.RotateAgentTokenResponse
	14, // 20: aegis.v2.CompanyService.RevokeAgentToken:output_type -> aegis.v2.RevokeAgentTokenResponse
	6,  // 21: aegis.v2.CompanyService.WatchCompanyUpdates:output_type -> aegis.v2.WatchCompanyUpdatesResponse
	3,  // 22: aegis.v2.CompanyService.ListAuditLogs:output_type -> aegis.v2.ListAuditLogsResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_aegis_v2_company_proto_init() }
func file_aegis_v2_company_proto_init() {
	if File_aegis_v2_company_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aegis_v2_company_proto_rawDesc), len(file_aegis_v2_company_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aegis_v2_company_proto_goTypes,
		DependencyIndexes: file_aegis_v2_company_proto_depIdxs,
		EnumInfos:         file_aegis_v2_company_proto_enumTypes,
		MessageInfos:      file_aegis_v2_company_proto_msgTypes,
	}.Build()
	File_aegis_v2_company_proto = out.File
	file_aegis_v2_company_proto_goTypes = nil
	file_aegis_v2_company_proto_depIdxs = nil
}
