// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aegis/v2/internal_auth.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenRequest) Reset() {
	*x = VerifyTokenRequest{}
	mi := &file_aegis_v2_internal_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRequest) ProtoMessage() {}

func (x *VerifyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_internal_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v2_internal_auth_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResponse) Reset() {
	*x = VerifyTokenResponse{}
	mi := &file_aegis_v2_internal_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResponse) ProtoMessage() {}

func (x *VerifyTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_internal_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v2_internal_auth_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyTokenResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

var File_aegis_v2_internal_auth_proto protoreflect.FileDescriptor

const file_aegis_v2_internal_auth_proto_rawDesc = "" +
	"\n" +
	"\x1caegis/v2/internal_auth.proto\x12\baegis.v2\"*\n" +
	"\x12VerifyTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"H\n" +
	"\x13VerifyTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId2a\n" +
	"\x13InternalAuthService\x12J\n" +
	"\vVerifyToken\x12\x1c.aegis.v2.VerifyTokenRequest\x1a\x1d.aegis.v2.VerifyTokenResponseBPZNgithub.com/Aegis-AI-Organizations/aegis-ai-api-gateway/internal/agrpc/aegis/v2b\x06proto3"

var (
	file_aegis_v2_internal_auth_proto_rawDescOnce sync.Once
	file_aegis_v2_internal_auth_proto_rawDescData []byte
)

func file_aegis_v2_internal_auth_proto_rawDescGZIP() []byte {
	file_aegis_v2_internal_auth_proto_rawDescOnce.Do(func() {
		file_aegis_v2_internal_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aegis_v2_internal_auth_proto_rawDesc), len(file_aegis_v2_internal_auth_proto_rawDesc)))
	})
	return file_aegis_v2_internal_auth_proto_rawDescData
}

var file_aegis_v2_internal_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aegis_v2_internal_auth_proto_goTypes = []any{
	(*VerifyTokenRequest)(nil),  // 0: aegis.v2.VerifyTokenRequest
	(*VerifyTokenResponse)(nil), // 1: aegis.v2.VerifyTokenResponse
}
var file_aegis_v2_internal_auth_proto_depIdxs = []int32{
	0, // 0: aegis.v2.InternalAuthService.VerifyToken:input_type -> aegis.v2.VerifyTokenRequest
	1, // 1: aegis.v2.InternalAuthService.VerifyToken:output_type -> aegis.v2.VerifyTokenResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aegis_v2_internal_auth_proto_init() }
func file_aegis_v2_internal_auth_proto_init() {
	if File_aegis_v2_internal_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aegis_v2_internal_auth_proto_rawDesc), len(file_aegis_v2_internal_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aegis_v2_internal_auth_proto_goTypes,
		DependencyIndexes: file_aegis_v2_internal_auth_proto_depIdxs,
		MessageInfos:      file_aegis_v2_internal_auth_proto_msgTypes,
	}.Build()
	File_aegis_v2_internal_auth_proto = out.File
	file_aegis_v2_internal_auth_proto_goTypes = nil
	file_aegis_v2_internal_auth_proto_depIdxs = nil
}
