// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aegis/v2/scan.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetImage   string                 `protobuf:"bytes,1,opt,name=target_image,json=targetImage,proto3" json:"target_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartScanRequest) Reset() {
	*x = StartScanRequest{}
	mi := &file_aegis_v2_scan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartScanRequest) ProtoMessage() {}

func (x *StartScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_scan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartScanRequest.ProtoReflect.Descriptor instead.
func (*StartScanRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v2_scan_proto_rawDescGZIP(), []int{0}
}

func (x *StartScanRequest) GetTargetImage() string {
	if x != nil {
		return x.TargetImage
	}
	return ""
}

type StartScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartScanResponse) Reset() {
	*x = StartScanResponse{}
	mi := &file_aegis_v2_scan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartScanResponse) ProtoMessage() {}

func (x *StartScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_scan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartScanResponse.ProtoReflect.Descriptor instead.
func (*StartScanResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v2_scan_proto_rawDescGZIP(), []int{1}
}

func (x *StartScanResponse) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *StartScanResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StartScanResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

type GetScanStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScanStatusRequest) Reset() {
	*x = GetScanStatusRequest{}
	mi := &file_aegis_v2_scan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScanStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScanStatusRequest) ProtoMessage() {}

func (x *GetScanStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_scan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScanStatusRequest.ProtoReflect.Descriptor instead.
func (*GetScanStatusRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v2_scan_proto_rawDescGZIP(), []int{2}
}

func (x *GetScanStatusRequest) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

type GetScanStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScanStatusResponse) Reset() {
	*x = GetScanStatusResponse{}
	mi := &file_aegis_v2_scan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScanStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScanStatusResponse) ProtoMessage() {}

func (x *GetScanStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_scan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScanStatusResponse.ProtoReflect.Descriptor instead.
func (*GetScanStatusResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v2_scan_proto_rawDescGZIP(), []int{3}
}

func (x *GetScanStatusResponse) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *GetScanStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetScanStatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *GetScanStatusResponse) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type ListScansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScansRequest) Reset() {
	*x = ListScansRequest{}
	mi := &file_aegis_v2_scan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScansRequest) ProtoMessage() {}

func (x *ListScansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_scan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScansRequest.ProtoReflect.Descriptor instead.
func (*ListScansRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v2_scan_proto_rawDescGZIP(), []int{4}
}

type ScanDetails struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ScanId             string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	TemporalWorkflowId string                 `protobuf:"bytes,2,opt,name=temporal_workflow_id,json=temporalWorkflowId,proto3" json:"temporal_workflow_id,omitempty"`
	TargetImage        string                 `protobuf:"bytes,3,opt,name=target_image,json=targetImage,proto3" json:"target_image,omitempty"`
	Status             string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ScanDetails) Reset() {
	*x = ScanDetails{}
	mi := &file_aegis_v2_scan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanDetails) ProtoMessage() {}

func (x *ScanDetails) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_scan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanDetails.ProtoReflect.Descriptor instead.
func (*ScanDetails) Descriptor() ([]byte, []int) {
	return file_aegis_v2_scan_proto_rawDescGZIP(), []int{5}
}

func (x *ScanDetails) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *ScanDetails) GetTemporalWorkflowId() string {
	if x != nil {
		return x.TemporalWorkflowId
	}
	return ""
}

func (x *ScanDetails) GetTargetImage() string {
	if x != nil {
		return x.TargetImage
	}
	return ""
}

func (x *ScanDetails) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScanDetails) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ScanDetails) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type ListScansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scans         []*ScanDetails         `protobuf:"bytes,1,rep,name=scans,proto3" json:"scans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScansResponse) Reset() {
	*x = ListScansResponse{}
	mi := &file_aegis_v2_scan_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScansResponse) ProtoMessage() {}

func (x *ListScansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_scan_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScansResponse.ProtoReflect.Descriptor instead.
func (*ListScansResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v2_scan_proto_rawDescGZIP(), []int{6}
}

func (x *ListScansResponse) GetScans() []*ScanDetails {
	if x != nil {
		return x.Scans
	}
	return nil
}

type GetScanReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScanReportRequest) Reset() {
	*x = GetScanReportRequest{}
	mi := &file_aegis_v2_scan_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScanReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScanReportRequest) ProtoMessage() {}

func (x *GetScanReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_scan_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScanReportRequest.ProtoReflect.Descriptor instead.
func (*GetScanReportRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v2_scan_proto_rawDescGZIP(), []int{7}
}

func (x *GetScanReportRequest) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

type GetScanReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PdfData       []byte                 `protobuf:"bytes,1,opt,name=pdf_data,json=pdfData,proto3" json:"pdf_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScanReportResponse) Reset() {
	*x = GetScanReportResponse{}
	mi := &file_aegis_v2_scan_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScanReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScanReportResponse) ProtoMessage() {}

func (x *GetScanReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_scan_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScanReportResponse.ProtoReflect.Descriptor instead.
func (*GetScanReportResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v2_scan_proto_rawDescGZIP(), []int{8}
}

func (x *GetScanReportResponse) GetPdfData() []byte {
	if x != nil {
		return x.PdfData
	}
	return nil
}

type WatchScanStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchScanStatusRequest) Reset() {
	*x = WatchScanStatusRequest{}
	mi := &file_aegis_v2_scan_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchScanStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchScanStatusRequest) ProtoMessage() {}

func (x *WatchScanStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_scan_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchScanStatusRequest.ProtoReflect.Descriptor instead.
func (*WatchScanStatusRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v2_scan_proto_rawDescGZIP(), []int{9}
}

func (x *WatchScanStatusRequest) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

type WatchScanStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchScanStatusResponse) Reset() {
	*x = WatchScanStatusResponse{}
	mi := &file_aegis_v2_scan_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchScanStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchScanStatusResponse) ProtoMessage() {}

func (x *WatchScanStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_scan_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchScanStatusResponse.ProtoReflect.Descriptor instead.
func (*WatchScanStatusResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v2_scan_proto_rawDescGZIP(), []int{10}
}

func (x *WatchScanStatusResponse) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *WatchScanStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_aegis_v2_scan_proto protoreflect.FileDescriptor

const file_aegis_v2_scan_proto_rawDesc = "" +
	"\n" +
	"\x13aegis/v2/scan.proto\x12\baegis.v2\x1a\x1fgoogle/protobuf/timestamp.proto\"5\n" +
	"\x10StartScanRequest\x12!\n" +
	"\ftarget_image\x18\x01 \x01(\tR\vtargetImage\"\x7f\n" +
	"\x11StartScanResponse\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"/\n" +
	"\x14GetScanStatusRequest\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\"\xc2\x01\n" +
	"\x15GetScanStatusResponse\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\x12\n" +
	"\x10ListScansRequest\"\x8d\x02\n" +
	"\vScanDetails\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x120\n" +
	"\x14temporal_workflow_id\x18\x02 \x01(\tR\x12temporalWorkflowId\x12!\n" +
	"\ftarget_image\x18\x03 \x01(\tR\vtargetImage\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"@\n" +
	"\x11ListScansResponse\x12+\n" +
	"\x05scans\x18\x01 \x03(\v2\x15.aegis.v2.ScanDetailsR\x05scans\"/\n" +
	"\x14GetScanReportRequest\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\"2\n" +
	"\x15GetScanReportResponse\x12\x19\n" +
	"\bpdf_data\x18\x01 \x01(\fR\apdfData\"1\n" +
	"\x16WatchScanStatusRequest\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\"J\n" +
	"\x17WatchScanStatusResponse\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\x97\x03\n" +
	"\vScanService\x12D\n" +
	"\tStartScan\x12\x1a.aegis.v2.StartScanRequest\x1a\x1b.aegis.v2.StartScanResponse\x12P\n" +
	"\rGetScanStatus\x12\x1e.aegis.v2.GetScanStatusRequest\x1a\x1f.aegis.v2.GetScanStatusResponse\x12D\n" +
	"\tListScans\x12\x1a.aegis.v2.ListScansRequest\x1a\x1b.aegis.v2.ListScansResponse\x12P\n" +
	"\rGetScanReport\x12\x1e.aegis.v2.GetScanReportRequest\x1a\x1f.aegis.v2.GetScanReportResponse\x12X\n" +
	"\x0fWatchScanStatus\x12 .aegis.v2.WatchScanStatusRequest\x1a!.aegis.v2.WatchScanStatusResponse0\x01B;Z9github.com/Aegis-AI-Organizations/aegis-ai-proto/aegis/v2b\x06proto3"

var (
	file_aegis_v2_scan_proto_rawDescOnce sync.Once
	file_aegis_v2_scan_proto_rawDescData []byte
)

func file_aegis_v2_scan_proto_rawDescGZIP() []byte {
	file_aegis_v2_scan_proto_rawDescOnce.Do(func() {
		file_aegis_v2_scan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aegis_v2_scan_proto_rawDesc), len(file_aegis_v2_scan_proto_rawDesc)))
	})
	return file_aegis_v2_scan_proto_rawDescData
}

var file_aegis_v2_scan_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_aegis_v2_scan_proto_goTypes = []any{
	(*StartScanRequest)(nil),        // 0: aegis.v2.StartScanRequest
	(*StartScanResponse)(nil),       // 1: aegis.v2.StartScanResponse
	(*GetScanStatusRequest)(nil),    // 2: aegis.v2.GetScanStatusRequest
	(*GetScanStatusResponse)(nil),   // 3: aegis.v2.GetScanStatusResponse
	(*ListScansRequest)(nil),        // 4: aegis.v2.ListScansRequest
	(*ScanDetails)(nil),             // 5: aegis.v2.ScanDetails
	(*ListScansResponse)(nil),       // 6: aegis.v2.ListScansResponse
	(*GetScanReportRequest)(nil),    // 7: aegis.v2.GetScanReportRequest
	(*GetScanReportResponse)(nil),   // 8: aegis.v2.GetScanReportResponse
	(*WatchScanStatusRequest)(nil),  // 9: aegis.v2.WatchScanStatusRequest
	(*WatchScanStatusResponse)(nil), // 10: aegis.v2.WatchScanStatusResponse
	(*timestamppb.Timestamp)(nil),   // 11: google.protobuf.Timestamp
}
var file_aegis_v2_scan_proto_depIdxs = []int32{
	11, // 0: aegis.v2.StartScanResponse.started_at:type_name -> google.protobuf.Timestamp
	11, // 1: aegis.v2.GetScanStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	11, // 2: aegis.v2.GetScanStatusResponse.completed_at:type_name -> google.protobuf.Timestamp
	11, // 3: aegis.v2.ScanDetails.started_at:type_name -> google.protobuf.Timestamp
	11, // 4: aegis.v2.ScanDetails.completed_at:type_name -> google.protobuf.Timestamp
	5,  // 5: aegis.v2.ListScansResponse.scans:type_name -> aegis.v2.ScanDetails
	0,  // 6: aegis.v2.ScanService.StartScan:input_type -> aegis.v2.StartScanRequest
	2,  // 7: aegis.v2.ScanService.GetScanStatus:input_type -> aegis.v2.GetScanStatusRequest
	4,  // 8: aegis.v2.ScanService.ListScans:input_type -> aegis.v2.ListScansRequest
	7,  // 9: aegis.v2.ScanService.GetScanReport:input_type -> aegis.v2.GetScanReportRequest
	9,  // 10: aegis.v2.ScanService.WatchScanStatus:input_type -> aegis.v2.WatchScanStatusRequest
	1,  // 11: aegis.v2.ScanService.StartScan:output_type -> aegis.v2.StartScanResponse
	3,  // 12: aegis.v2.ScanService.GetScanStatus:output_type -> aegis.v2.GetScanStatusResponse
	6,  // 13: aegis.v2.ScanService.ListScans:output_type -> aegis.v2.ListScansResponse
	8,  // 14: aegis.v2.ScanService.GetScanReport:output_type -> aegis.v2.GetScanReportResponse
	10, // 15: aegis.v2.ScanService.WatchScanStatus:output_type -> aegis.v2.WatchScanStatusResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_aegis_v2_scan_proto_init() }
func file_aegis_v2_scan_proto_init() {
	if File_aegis_v2_scan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aegis_v2_scan_proto_rawDesc), len(file_aegis_v2_scan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aegis_v2_scan_proto_goTypes,
		DependencyIndexes: file_aegis_v2_scan_proto_depIdxs,
		MessageInfos:      file_aegis_v2_scan_proto_msgTypes,
	}.Build()
	File_aegis_v2_scan_proto = out.File
	file_aegis_v2_scan_proto_goTypes = nil
	file_aegis_v2_scan_proto_depIdxs = nil
}
