// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aegis/v2/topology.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportTopologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topology      *NetworkTopology       `protobuf:"bytes,1,opt,name=topology,proto3" json:"topology,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTopologyRequest) Reset() {
	*x = ReportTopologyRequest{}
	mi := &file_aegis_v2_topology_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTopologyRequest) ProtoMessage() {}

func (x *ReportTopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_topology_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTopologyRequest.ProtoReflect.Descriptor instead.
func (*ReportTopologyRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v2_topology_proto_rawDescGZIP(), []int{0}
}

func (x *ReportTopologyRequest) GetTopology() *NetworkTopology {
	if x != nil {
		return x.Topology
	}
	return nil
}

type ReportTopologyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTopologyResponse) Reset() {
	*x = ReportTopologyResponse{}
	mi := &file_aegis_v2_topology_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTopologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTopologyResponse) ProtoMessage() {}

func (x *ReportTopologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_topology_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTopologyResponse.ProtoReflect.Descriptor instead.
func (*ReportTopologyResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v2_topology_proto_rawDescGZIP(), []int{1}
}

func (x *ReportTopologyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// NetworkTopology represents the scanned infrastructure state.
type NetworkTopology struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []*Host                `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkTopology) Reset() {
	*x = NetworkTopology{}
	mi := &file_aegis_v2_topology_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkTopology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkTopology) ProtoMessage() {}

func (x *NetworkTopology) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_topology_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkTopology.ProtoReflect.Descriptor instead.
func (*NetworkTopology) Descriptor() ([]byte, []int) {
	return file_aegis_v2_topology_proto_rawDescGZIP(), []int{2}
}

func (x *NetworkTopology) GetHosts() []*Host {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type Host struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddresses   []string               `protobuf:"bytes,3,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
	Containers    []*Container           `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	Processes     []*Process             `protobuf:"bytes,5,rep,name=processes,proto3" json:"processes,omitempty"` // Processes running directly on the host
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_aegis_v2_topology_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_topology_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_aegis_v2_topology_proto_rawDescGZIP(), []int{3}
}

func (x *Host) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Host) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Host) GetIpAddresses() []string {
	if x != nil {
		return x.IpAddresses
	}
	return nil
}

func (x *Host) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *Host) GetProcesses() []*Process {
	if x != nil {
		return x.Processes
	}
	return nil
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Processes     []*Process             `protobuf:"bytes,4,rep,name=processes,proto3" json:"processes,omitempty"`
	Ports         []*Port                `protobuf:"bytes,5,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_aegis_v2_topology_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_topology_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_aegis_v2_topology_proto_rawDescGZIP(), []int{4}
}

func (x *Container) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Container) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Container) GetProcesses() []*Process {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *Container) GetPorts() []*Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

type Process struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CommandLine   *string                `protobuf:"bytes,3,opt,name=command_line,json=commandLine,proto3,oneof" json:"command_line,omitempty"`
	User          *string                `protobuf:"bytes,4,opt,name=user,proto3,oneof" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Process) Reset() {
	*x = Process{}
	mi := &file_aegis_v2_topology_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_topology_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_aegis_v2_topology_proto_rawDescGZIP(), []int{5}
}

func (x *Process) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Process) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Process) GetCommandLine() string {
	if x != nil && x.CommandLine != nil {
		return *x.CommandLine
	}
	return ""
}

func (x *Process) GetUser() string {
	if x != nil && x.User != nil {
		return *x.User
	}
	return ""
}

type Port struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"` // e.g., "tcp", "udp"
	State         *string                `protobuf:"bytes,3,opt,name=state,proto3,oneof" json:"state,omitempty"` // e.g., "LISTEN", "ESTABLISHED"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Port) Reset() {
	*x = Port{}
	mi := &file_aegis_v2_topology_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Port) ProtoMessage() {}

func (x *Port) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_topology_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Port.ProtoReflect.Descriptor instead.
func (*Port) Descriptor() ([]byte, []int) {
	return file_aegis_v2_topology_proto_rawDescGZIP(), []int{6}
}

func (x *Port) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Port) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Port) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

var File_aegis_v2_topology_proto protoreflect.FileDescriptor

const file_aegis_v2_topology_proto_rawDesc = "" +
	"\n" +
	"\x17aegis/v2/topology.proto\x12\baegis.v2\"N\n" +
	"\x15ReportTopologyRequest\x125\n" +
	"\btopology\x18\x01 \x01(\v2\x19.aegis.v2.NetworkTopologyR\btopology\"2\n" +
	"\x16ReportTopologyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"7\n" +
	"\x0fNetworkTopology\x12$\n" +
	"\x05hosts\x18\x01 \x03(\v2\x0e.aegis.v2.HostR\x05hosts\"\xbb\x01\n" +
	"\x04Host\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12!\n" +
	"\fip_addresses\x18\x03 \x03(\tR\vipAddresses\x123\n" +
	"\n" +
	"containers\x18\x04 \x03(\v2\x13.aegis.v2.ContainerR\n" +
	"containers\x12/\n" +
	"\tprocesses\x18\x05 \x03(\v2\x11.aegis.v2.ProcessR\tprocesses\"\x9c\x01\n" +
	"\tContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12/\n" +
	"\tprocesses\x18\x04 \x03(\v2\x11.aegis.v2.ProcessR\tprocesses\x12$\n" +
	"\x05ports\x18\x05 \x03(\v2\x0e.aegis.v2.PortR\x05ports\"\x8a\x01\n" +
	"\aProcess\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\fcommand_line\x18\x03 \x01(\tH\x00R\vcommandLine\x88\x01\x01\x12\x17\n" +
	"\x04user\x18\x04 \x01(\tH\x01R\x04user\x88\x01\x01B\x0f\n" +
	"\r_command_lineB\a\n" +
	"\x05_user\"_\n" +
	"\x04Port\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x19\n" +
	"\x05state\x18\x03 \x01(\tH\x00R\x05state\x88\x01\x01B\b\n" +
	"\x06_state2f\n" +
	"\x0fTopologyService\x12S\n" +
	"\x0eReportTopology\x12\x1f.aegis.v2.ReportTopologyRequest\x1a .aegis.v2.ReportTopologyResponseBPZNgithub.com/Aegis-AI-Organizations/aegis-ai-api-gateway/internal/agrpc/aegis/v2b\x06proto3"

var (
	file_aegis_v2_topology_proto_rawDescOnce sync.Once
	file_aegis_v2_topology_proto_rawDescData []byte
)

func file_aegis_v2_topology_proto_rawDescGZIP() []byte {
	file_aegis_v2_topology_proto_rawDescOnce.Do(func() {
		file_aegis_v2_topology_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aegis_v2_topology_proto_rawDesc), len(file_aegis_v2_topology_proto_rawDesc)))
	})
	return file_aegis_v2_topology_proto_rawDescData
}

var file_aegis_v2_topology_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_aegis_v2_topology_proto_goTypes = []any{
	(*ReportTopologyRequest)(nil),  // 0: aegis.v2.ReportTopologyRequest
	(*ReportTopologyResponse)(nil), // 1: aegis.v2.ReportTopologyResponse
	(*NetworkTopology)(nil),        // 2: aegis.v2.NetworkTopology
	(*Host)(nil),                   // 3: aegis.v2.Host
	(*Container)(nil),              // 4: aegis.v2.Container
	(*Process)(nil),                // 5: aegis.v2.Process
	(*Port)(nil),                   // 6: aegis.v2.Port
}
var file_aegis_v2_topology_proto_depIdxs = []int32{
	2, // 0: aegis.v2.ReportTopologyRequest.topology:type_name -> aegis.v2.NetworkTopology
	3, // 1: aegis.v2.NetworkTopology.hosts:type_name -> aegis.v2.Host
	4, // 2: aegis.v2.Host.containers:type_name -> aegis.v2.Container
	5, // 3: aegis.v2.Host.processes:type_name -> aegis.v2.Process
	5, // 4: aegis.v2.Container.processes:type_name -> aegis.v2.Process
	6, // 5: aegis.v2.Container.ports:type_name -> aegis.v2.Port
	0, // 6: aegis.v2.TopologyService.ReportTopology:input_type -> aegis.v2.ReportTopologyRequest
	1, // 7: aegis.v2.TopologyService.ReportTopology:output_type -> aegis.v2.ReportTopologyResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_aegis_v2_topology_proto_init() }
func file_aegis_v2_topology_proto_init() {
	if File_aegis_v2_topology_proto != nil {
		return
	}
	file_aegis_v2_topology_proto_msgTypes[5].OneofWrappers = []any{}
	file_aegis_v2_topology_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aegis_v2_topology_proto_rawDesc), len(file_aegis_v2_topology_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aegis_v2_topology_proto_goTypes,
		DependencyIndexes: file_aegis_v2_topology_proto_depIdxs,
		MessageInfos:      file_aegis_v2_topology_proto_msgTypes,
	}.Build()
	File_aegis_v2_topology_proto = out.File
	file_aegis_v2_topology_proto_goTypes = nil
	file_aegis_v2_topology_proto_depIdxs = nil
}
