// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: aegis/v2/topology.proto

package v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TopologyService_ReportTopology_FullMethodName = "/aegis.v2.TopologyService/ReportTopology"
)

// TopologyServiceClient is the client API for TopologyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TopologyService allows agents to export infrastructure data (hosts, containers, processes).
type TopologyServiceClient interface {
	// ReportTopology sends the discovered infrastructure state to the SaaS.
	ReportTopology(ctx context.Context, in *ReportTopologyRequest, opts ...grpc.CallOption) (*ReportTopologyResponse, error)
}

type topologyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTopologyServiceClient(cc grpc.ClientConnInterface) TopologyServiceClient {
	return &topologyServiceClient{cc}
}

func (c *topologyServiceClient) ReportTopology(ctx context.Context, in *ReportTopologyRequest, opts ...grpc.CallOption) (*ReportTopologyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportTopologyResponse)
	err := c.cc.Invoke(ctx, TopologyService_ReportTopology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TopologyServiceServer is the server API for TopologyService service.
// All implementations must embed UnimplementedTopologyServiceServer
// for forward compatibility.
//
// TopologyService allows agents to export infrastructure data (hosts, containers, processes).
type TopologyServiceServer interface {
	// ReportTopology sends the discovered infrastructure state to the SaaS.
	ReportTopology(context.Context, *ReportTopologyRequest) (*ReportTopologyResponse, error)
	mustEmbedUnimplementedTopologyServiceServer()
}

// UnimplementedTopologyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTopologyServiceServer struct{}

func (UnimplementedTopologyServiceServer) ReportTopology(context.Context, *ReportTopologyRequest) (*ReportTopologyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTopology not implemented")
}
func (UnimplementedTopologyServiceServer) mustEmbedUnimplementedTopologyServiceServer() {}
func (UnimplementedTopologyServiceServer) testEmbeddedByValue()                         {}

// UnsafeTopologyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TopologyServiceServer will
// result in compilation errors.
type UnsafeTopologyServiceServer interface {
	mustEmbedUnimplementedTopologyServiceServer()
}

func RegisterTopologyServiceServer(s grpc.ServiceRegistrar, srv TopologyServiceServer) {
	// If the following call panics, it indicates UnimplementedTopologyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TopologyService_ServiceDesc, srv)
}

func _TopologyService_ReportTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportTopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyServiceServer).ReportTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyService_ReportTopology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyServiceServer).ReportTopology(ctx, req.(*ReportTopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TopologyService_ServiceDesc is the grpc.ServiceDesc for TopologyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TopologyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aegis.v2.TopologyService",
	HandlerType: (*TopologyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportTopology",
			Handler:    _TopologyService_ReportTopology_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aegis/v2/topology.proto",
}
