// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aegis/v2/billing.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_aegis_v2_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v2_billing_proto_rawDescGZIP(), []int{0}
}

func (x *GetBalanceRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_aegis_v2_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v2_billing_proto_rawDescGZIP(), []int{1}
}

func (x *GetBalanceResponse) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *GetBalanceResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type GetLedgerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLedgerRequest) Reset() {
	*x = GetLedgerRequest{}
	mi := &file_aegis_v2_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerRequest) ProtoMessage() {}

func (x *GetLedgerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerRequest.ProtoReflect.Descriptor instead.
func (*GetLedgerRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v2_billing_proto_rawDescGZIP(), []int{2}
}

func (x *GetLedgerRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *GetLedgerRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetLedgerRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetLedgerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LedgerEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLedgerResponse) Reset() {
	*x = GetLedgerResponse{}
	mi := &file_aegis_v2_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerResponse) ProtoMessage() {}

func (x *GetLedgerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerResponse.ProtoReflect.Descriptor instead.
func (*GetLedgerResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v2_billing_proto_rawDescGZIP(), []int{3}
}

func (x *GetLedgerResponse) GetEntries() []*LedgerEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetLedgerResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type LedgerEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	ScanId        string                 `protobuf:"bytes,5,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"` // Optional
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerEntry) Reset() {
	*x = LedgerEntry{}
	mi := &file_aegis_v2_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerEntry) ProtoMessage() {}

func (x *LedgerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerEntry.ProtoReflect.Descriptor instead.
func (*LedgerEntry) Descriptor() ([]byte, []int) {
	return file_aegis_v2_billing_proto_rawDescGZIP(), []int{4}
}

func (x *LedgerEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LedgerEntry) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *LedgerEntry) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *LedgerEntry) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *LedgerEntry) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *LedgerEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type AdjustTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustTokensRequest) Reset() {
	*x = AdjustTokensRequest{}
	mi := &file_aegis_v2_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustTokensRequest) ProtoMessage() {}

func (x *AdjustTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustTokensRequest.ProtoReflect.Descriptor instead.
func (*AdjustTokensRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v2_billing_proto_rawDescGZIP(), []int{5}
}

func (x *AdjustTokensRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *AdjustTokensRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AdjustTokensRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AdjustTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustTokensResponse) Reset() {
	*x = AdjustTokensResponse{}
	mi := &file_aegis_v2_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustTokensResponse) ProtoMessage() {}

func (x *AdjustTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustTokensResponse.ProtoReflect.Descriptor instead.
func (*AdjustTokensResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v2_billing_proto_rawDescGZIP(), []int{6}
}

func (x *AdjustTokensResponse) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *AdjustTokensResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type PreFlightCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	TargetConfig  *TargetConfig          `protobuf:"bytes,2,opt,name=target_config,json=targetConfig,proto3" json:"target_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreFlightCheckRequest) Reset() {
	*x = PreFlightCheckRequest{}
	mi := &file_aegis_v2_billing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreFlightCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreFlightCheckRequest) ProtoMessage() {}

func (x *PreFlightCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_billing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreFlightCheckRequest.ProtoReflect.Descriptor instead.
func (*PreFlightCheckRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v2_billing_proto_rawDescGZIP(), []int{7}
}

func (x *PreFlightCheckRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *PreFlightCheckRequest) GetTargetConfig() *TargetConfig {
	if x != nil {
		return x.TargetConfig
	}
	return nil
}

type TargetConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpCount       int32                  `protobuf:"varint,1,opt,name=ip_count,json=ipCount,proto3" json:"ip_count,omitempty"`
	ApiCount      int32                  `protobuf:"varint,2,opt,name=api_count,json=apiCount,proto3" json:"api_count,omitempty"`
	WebappCount   int32                  `protobuf:"varint,3,opt,name=webapp_count,json=webappCount,proto3" json:"webapp_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetConfig) Reset() {
	*x = TargetConfig{}
	mi := &file_aegis_v2_billing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetConfig) ProtoMessage() {}

func (x *TargetConfig) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_billing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetConfig.ProtoReflect.Descriptor instead.
func (*TargetConfig) Descriptor() ([]byte, []int) {
	return file_aegis_v2_billing_proto_rawDescGZIP(), []int{8}
}

func (x *TargetConfig) GetIpCount() int32 {
	if x != nil {
		return x.IpCount
	}
	return 0
}

func (x *TargetConfig) GetApiCount() int32 {
	if x != nil {
		return x.ApiCount
	}
	return 0
}

func (x *TargetConfig) GetWebappCount() int32 {
	if x != nil {
		return x.WebappCount
	}
	return 0
}

type PreFlightCheckResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SufficientBalance bool                   `protobuf:"varint,1,opt,name=sufficient_balance,json=sufficientBalance,proto3" json:"sufficient_balance,omitempty"`
	EstimatedCost     int64                  `protobuf:"varint,2,opt,name=estimated_cost,json=estimatedCost,proto3" json:"estimated_cost,omitempty"`
	CurrentBalance    int64                  `protobuf:"varint,3,opt,name=current_balance,json=currentBalance,proto3" json:"current_balance,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PreFlightCheckResponse) Reset() {
	*x = PreFlightCheckResponse{}
	mi := &file_aegis_v2_billing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreFlightCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreFlightCheckResponse) ProtoMessage() {}

func (x *PreFlightCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v2_billing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreFlightCheckResponse.ProtoReflect.Descriptor instead.
func (*PreFlightCheckResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v2_billing_proto_rawDescGZIP(), []int{9}
}

func (x *PreFlightCheckResponse) GetSufficientBalance() bool {
	if x != nil {
		return x.SufficientBalance
	}
	return false
}

func (x *PreFlightCheckResponse) GetEstimatedCost() int64 {
	if x != nil {
		return x.EstimatedCost
	}
	return 0
}

func (x *PreFlightCheckResponse) GetCurrentBalance() int64 {
	if x != nil {
		return x.CurrentBalance
	}
	return 0
}

var File_aegis_v2_billing_proto protoreflect.FileDescriptor

const file_aegis_v2_billing_proto_rawDesc = "" +
	"\n" +
	"\x16aegis/v2/billing.proto\x12\baegis.v2\x1a\x1fgoogle/protobuf/timestamp.proto\"2\n" +
	"\x11GetBalanceRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\"M\n" +
	"\x12GetBalanceResponse\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\"_\n" +
	"\x10GetLedgerRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"Z\n" +
	"\x11GetLedgerResponse\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.aegis.v2.LedgerEntryR\aentries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xc0\x01\n" +
	"\vLedgerEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x17\n" +
	"\ascan_id\x18\x05 \x01(\tR\x06scanId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"d\n" +
	"\x13AdjustTokensRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"O\n" +
	"\x14AdjustTokensResponse\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\"s\n" +
	"\x15PreFlightCheckRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12;\n" +
	"\rtarget_config\x18\x02 \x01(\v2\x16.aegis.v2.TargetConfigR\ftargetConfig\"i\n" +
	"\fTargetConfig\x12\x19\n" +
	"\bip_count\x18\x01 \x01(\x05R\aipCount\x12\x1b\n" +
	"\tapi_count\x18\x02 \x01(\x05R\bapiCount\x12!\n" +
	"\fwebapp_count\x18\x03 \x01(\x05R\vwebappCount\"\x97\x01\n" +
	"\x16PreFlightCheckResponse\x12-\n" +
	"\x12sufficient_balance\x18\x01 \x01(\bR\x11sufficientBalance\x12%\n" +
	"\x0eestimated_cost\x18\x02 \x01(\x03R\restimatedCost\x12'\n" +
	"\x0fcurrent_balance\x18\x03 \x01(\x03R\x0ecurrentBalance2\xc3\x02\n" +
	"\x0eBillingService\x12G\n" +
	"\n" +
	"GetBalance\x12\x1b.aegis.v2.GetBalanceRequest\x1a\x1c.aegis.v2.GetBalanceResponse\x12D\n" +
	"\tGetLedger\x12\x1a.aegis.v2.GetLedgerRequest\x1a\x1b.aegis.v2.GetLedgerResponse\x12M\n" +
	"\fAdjustTokens\x12\x1d.aegis.v2.AdjustTokensRequest\x1a\x1e.aegis.v2.AdjustTokensResponse\x12S\n" +
	"\x0ePreFlightCheck\x12\x1f.aegis.v2.PreFlightCheckRequest\x1a .aegis.v2.PreFlightCheckResponseBPZNgithub.com/Aegis-AI-Organizations/aegis-ai-api-gateway/internal/agrpc/aegis/v2b\x06proto3"

var (
	file_aegis_v2_billing_proto_rawDescOnce sync.Once
	file_aegis_v2_billing_proto_rawDescData []byte
)

func file_aegis_v2_billing_proto_rawDescGZIP() []byte {
	file_aegis_v2_billing_proto_rawDescOnce.Do(func() {
		file_aegis_v2_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aegis_v2_billing_proto_rawDesc), len(file_aegis_v2_billing_proto_rawDesc)))
	})
	return file_aegis_v2_billing_proto_rawDescData
}

var file_aegis_v2_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_aegis_v2_billing_proto_goTypes = []any{
	(*GetBalanceRequest)(nil),      // 0: aegis.v2.GetBalanceRequest
	(*GetBalanceResponse)(nil),     // 1: aegis.v2.GetBalanceResponse
	(*GetLedgerRequest)(nil),       // 2: aegis.v2.GetLedgerRequest
	(*GetLedgerResponse)(nil),      // 3: aegis.v2.GetLedgerResponse
	(*LedgerEntry)(nil),            // 4: aegis.v2.LedgerEntry
	(*AdjustTokensRequest)(nil),    // 5: aegis.v2.AdjustTokensRequest
	(*AdjustTokensResponse)(nil),   // 6: aegis.v2.AdjustTokensResponse
	(*PreFlightCheckRequest)(nil),  // 7: aegis.v2.PreFlightCheckRequest
	(*TargetConfig)(nil),           // 8: aegis.v2.TargetConfig
	(*PreFlightCheckResponse)(nil), // 9: aegis.v2.PreFlightCheckResponse
	(*timestamppb.Timestamp)(nil),  // 10: google.protobuf.Timestamp
}
var file_aegis_v2_billing_proto_depIdxs = []int32{
	4,  // 0: aegis.v2.GetLedgerResponse.entries:type_name -> aegis.v2.LedgerEntry
	10, // 1: aegis.v2.LedgerEntry.created_at:type_name -> google.protobuf.Timestamp
	8,  // 2: aegis.v2.PreFlightCheckRequest.target_config:type_name -> aegis.v2.TargetConfig
	0,  // 3: aegis.v2.BillingService.GetBalance:input_type -> aegis.v2.GetBalanceRequest
	2,  // 4: aegis.v2.BillingService.GetLedger:input_type -> aegis.v2.GetLedgerRequest
	5,  // 5: aegis.v2.BillingService.AdjustTokens:input_type -> aegis.v2.AdjustTokensRequest
	7,  // 6: aegis.v2.BillingService.PreFlightCheck:input_type -> aegis.v2.PreFlightCheckRequest
	1,  // 7: aegis.v2.BillingService.GetBalance:output_type -> aegis.v2.GetBalanceResponse
	3,  // 8: aegis.v2.BillingService.GetLedger:output_type -> aegis.v2.GetLedgerResponse
	6,  // 9: aegis.v2.BillingService.AdjustTokens:output_type -> aegis.v2.AdjustTokensResponse
	9,  // 10: aegis.v2.BillingService.PreFlightCheck:output_type -> aegis.v2.PreFlightCheckResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_aegis_v2_billing_proto_init() }
func file_aegis_v2_billing_proto_init() {
	if File_aegis_v2_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aegis_v2_billing_proto_rawDesc), len(file_aegis_v2_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aegis_v2_billing_proto_goTypes,
		DependencyIndexes: file_aegis_v2_billing_proto_depIdxs,
		MessageInfos:      file_aegis_v2_billing_proto_msgTypes,
	}.Build()
	File_aegis_v2_billing_proto = out.File
	file_aegis_v2_billing_proto_goTypes = nil
	file_aegis_v2_billing_proto_depIdxs = nil
}
