// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: aegis/v2/billing.proto

package v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BillingService_GetBalance_FullMethodName     = "/aegis.v2.BillingService/GetBalance"
	BillingService_GetLedger_FullMethodName      = "/aegis.v2.BillingService/GetLedger"
	BillingService_AdjustTokens_FullMethodName   = "/aegis.v2.BillingService/AdjustTokens"
	BillingService_PreFlightCheck_FullMethodName = "/aegis.v2.BillingService/PreFlightCheck"
	BillingService_GetUsageStats_FullMethodName  = "/aegis.v2.BillingService/GetUsageStats"
)

// BillingServiceClient is the client API for BillingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BillingService handles token management and consumption history.
type BillingServiceClient interface {
	// GetBalance retrieves the current token balance for a company.
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	// GetLedger retrieves the history of token transactions for a company.
	GetLedger(ctx context.Context, in *GetLedgerRequest, opts ...grpc.CallOption) (*GetLedgerResponse, error)
	// AdjustTokens adds or subtracts tokens from a company's balance.
	AdjustTokens(ctx context.Context, in *AdjustTokensRequest, opts ...grpc.CallOption) (*AdjustTokensResponse, error)
	// PreFlightCheck estimates the cost of a scan and checks if the balance is sufficient.
	PreFlightCheck(ctx context.Context, in *PreFlightCheckRequest, opts ...grpc.CallOption) (*PreFlightCheckResponse, error)
	// GetUsageStats retrieves aggregated consumption data for graphs.
	GetUsageStats(ctx context.Context, in *GetUsageStatsRequest, opts ...grpc.CallOption) (*GetUsageStatsResponse, error)
}

type billingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingServiceClient(cc grpc.ClientConnInterface) BillingServiceClient {
	return &billingServiceClient{cc}
}

func (c *billingServiceClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, BillingService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetLedger(ctx context.Context, in *GetLedgerRequest, opts ...grpc.CallOption) (*GetLedgerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLedgerResponse)
	err := c.cc.Invoke(ctx, BillingService_GetLedger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) AdjustTokens(ctx context.Context, in *AdjustTokensRequest, opts ...grpc.CallOption) (*AdjustTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdjustTokensResponse)
	err := c.cc.Invoke(ctx, BillingService_AdjustTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) PreFlightCheck(ctx context.Context, in *PreFlightCheckRequest, opts ...grpc.CallOption) (*PreFlightCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreFlightCheckResponse)
	err := c.cc.Invoke(ctx, BillingService_PreFlightCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetUsageStats(ctx context.Context, in *GetUsageStatsRequest, opts ...grpc.CallOption) (*GetUsageStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsageStatsResponse)
	err := c.cc.Invoke(ctx, BillingService_GetUsageStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingServiceServer is the server API for BillingService service.
// All implementations must embed UnimplementedBillingServiceServer
// for forward compatibility.
//
// BillingService handles token management and consumption history.
type BillingServiceServer interface {
	// GetBalance retrieves the current token balance for a company.
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	// GetLedger retrieves the history of token transactions for a company.
	GetLedger(context.Context, *GetLedgerRequest) (*GetLedgerResponse, error)
	// AdjustTokens adds or subtracts tokens from a company's balance.
	AdjustTokens(context.Context, *AdjustTokensRequest) (*AdjustTokensResponse, error)
	// PreFlightCheck estimates the cost of a scan and checks if the balance is sufficient.
	PreFlightCheck(context.Context, *PreFlightCheckRequest) (*PreFlightCheckResponse, error)
	// GetUsageStats retrieves aggregated consumption data for graphs.
	GetUsageStats(context.Context, *GetUsageStatsRequest) (*GetUsageStatsResponse, error)
	mustEmbedUnimplementedBillingServiceServer()
}

// UnimplementedBillingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBillingServiceServer struct{}

func (UnimplementedBillingServiceServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedBillingServiceServer) GetLedger(context.Context, *GetLedgerRequest) (*GetLedgerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLedger not implemented")
}
func (UnimplementedBillingServiceServer) AdjustTokens(context.Context, *AdjustTokensRequest) (*AdjustTokensResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdjustTokens not implemented")
}
func (UnimplementedBillingServiceServer) PreFlightCheck(context.Context, *PreFlightCheckRequest) (*PreFlightCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PreFlightCheck not implemented")
}
func (UnimplementedBillingServiceServer) GetUsageStats(context.Context, *GetUsageStatsRequest) (*GetUsageStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsageStats not implemented")
}
func (UnimplementedBillingServiceServer) mustEmbedUnimplementedBillingServiceServer() {}
func (UnimplementedBillingServiceServer) testEmbeddedByValue()                        {}

// UnsafeBillingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingServiceServer will
// result in compilation errors.
type UnsafeBillingServiceServer interface {
	mustEmbedUnimplementedBillingServiceServer()
}

func RegisterBillingServiceServer(s grpc.ServiceRegistrar, srv BillingServiceServer) {
	// If the following call panics, it indicates UnimplementedBillingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BillingService_ServiceDesc, srv)
}

func _BillingService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLedgerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetLedger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetLedger(ctx, req.(*GetLedgerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_AdjustTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdjustTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).AdjustTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_AdjustTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).AdjustTokens(ctx, req.(*AdjustTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_PreFlightCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreFlightCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).PreFlightCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_PreFlightCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).PreFlightCheck(ctx, req.(*PreFlightCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetUsageStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsageStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetUsageStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetUsageStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetUsageStats(ctx, req.(*GetUsageStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BillingService_ServiceDesc is the grpc.ServiceDesc for BillingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aegis.v2.BillingService",
	HandlerType: (*BillingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBalance",
			Handler:    _BillingService_GetBalance_Handler,
		},
		{
			MethodName: "GetLedger",
			Handler:    _BillingService_GetLedger_Handler,
		},
		{
			MethodName: "AdjustTokens",
			Handler:    _BillingService_AdjustTokens_Handler,
		},
		{
			MethodName: "PreFlightCheck",
			Handler:    _BillingService_PreFlightCheck_Handler,
		},
		{
			MethodName: "GetUsageStats",
			Handler:    _BillingService_GetUsageStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aegis/v2/billing.proto",
}
