// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: aegis/v2/scan.proto

package v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScanService_StartScan_FullMethodName       = "/aegis.v2.ScanService/StartScan"
	ScanService_GetScanStatus_FullMethodName   = "/aegis.v2.ScanService/GetScanStatus"
	ScanService_ListScans_FullMethodName       = "/aegis.v2.ScanService/ListScans"
	ScanService_GetScanReport_FullMethodName   = "/aegis.v2.ScanService/GetScanReport"
	ScanService_WatchScanStatus_FullMethodName = "/aegis.v2.ScanService/WatchScanStatus"
)

// ScanServiceClient is the client API for ScanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScanServiceClient interface {
	StartScan(ctx context.Context, in *StartScanRequest, opts ...grpc.CallOption) (*StartScanResponse, error)
	GetScanStatus(ctx context.Context, in *GetScanStatusRequest, opts ...grpc.CallOption) (*GetScanStatusResponse, error)
	ListScans(ctx context.Context, in *ListScansRequest, opts ...grpc.CallOption) (*ListScansResponse, error)
	GetScanReport(ctx context.Context, in *GetScanReportRequest, opts ...grpc.CallOption) (*GetScanReportResponse, error)
	WatchScanStatus(ctx context.Context, in *WatchScanStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchScanStatusResponse], error)
}

type scanServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScanServiceClient(cc grpc.ClientConnInterface) ScanServiceClient {
	return &scanServiceClient{cc}
}

func (c *scanServiceClient) StartScan(ctx context.Context, in *StartScanRequest, opts ...grpc.CallOption) (*StartScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartScanResponse)
	err := c.cc.Invoke(ctx, ScanService_StartScan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scanServiceClient) GetScanStatus(ctx context.Context, in *GetScanStatusRequest, opts ...grpc.CallOption) (*GetScanStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScanStatusResponse)
	err := c.cc.Invoke(ctx, ScanService_GetScanStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scanServiceClient) ListScans(ctx context.Context, in *ListScansRequest, opts ...grpc.CallOption) (*ListScansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListScansResponse)
	err := c.cc.Invoke(ctx, ScanService_ListScans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scanServiceClient) GetScanReport(ctx context.Context, in *GetScanReportRequest, opts ...grpc.CallOption) (*GetScanReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScanReportResponse)
	err := c.cc.Invoke(ctx, ScanService_GetScanReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scanServiceClient) WatchScanStatus(ctx context.Context, in *WatchScanStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchScanStatusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ScanService_ServiceDesc.Streams[0], ScanService_WatchScanStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchScanStatusRequest, WatchScanStatusResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ScanService_WatchScanStatusClient = grpc.ServerStreamingClient[WatchScanStatusResponse]

// ScanServiceServer is the server API for ScanService service.
// All implementations must embed UnimplementedScanServiceServer
// for forward compatibility.
type ScanServiceServer interface {
	StartScan(context.Context, *StartScanRequest) (*StartScanResponse, error)
	GetScanStatus(context.Context, *GetScanStatusRequest) (*GetScanStatusResponse, error)
	ListScans(context.Context, *ListScansRequest) (*ListScansResponse, error)
	GetScanReport(context.Context, *GetScanReportRequest) (*GetScanReportResponse, error)
	WatchScanStatus(*WatchScanStatusRequest, grpc.ServerStreamingServer[WatchScanStatusResponse]) error
	mustEmbedUnimplementedScanServiceServer()
}

// UnimplementedScanServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScanServiceServer struct{}

func (UnimplementedScanServiceServer) StartScan(context.Context, *StartScanRequest) (*StartScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartScan not implemented")
}
func (UnimplementedScanServiceServer) GetScanStatus(context.Context, *GetScanStatusRequest) (*GetScanStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScanStatus not implemented")
}
func (UnimplementedScanServiceServer) ListScans(context.Context, *ListScansRequest) (*ListScansResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListScans not implemented")
}
func (UnimplementedScanServiceServer) GetScanReport(context.Context, *GetScanReportRequest) (*GetScanReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScanReport not implemented")
}
func (UnimplementedScanServiceServer) WatchScanStatus(*WatchScanStatusRequest, grpc.ServerStreamingServer[WatchScanStatusResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchScanStatus not implemented")
}
func (UnimplementedScanServiceServer) mustEmbedUnimplementedScanServiceServer() {}
func (UnimplementedScanServiceServer) testEmbeddedByValue()                     {}

// UnsafeScanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScanServiceServer will
// result in compilation errors.
type UnsafeScanServiceServer interface {
	mustEmbedUnimplementedScanServiceServer()
}

func RegisterScanServiceServer(s grpc.ServiceRegistrar, srv ScanServiceServer) {
	// If the following call panics, it indicates UnimplementedScanServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScanService_ServiceDesc, srv)
}

func _ScanService_StartScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScanServiceServer).StartScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScanService_StartScan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScanServiceServer).StartScan(ctx, req.(*StartScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScanService_GetScanStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScanStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScanServiceServer).GetScanStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScanService_GetScanStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScanServiceServer).GetScanStatus(ctx, req.(*GetScanStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScanService_ListScans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScanServiceServer).ListScans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScanService_ListScans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScanServiceServer).ListScans(ctx, req.(*ListScansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScanService_GetScanReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScanReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScanServiceServer).GetScanReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScanService_GetScanReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScanServiceServer).GetScanReport(ctx, req.(*GetScanReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScanService_WatchScanStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchScanStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ScanServiceServer).WatchScanStatus(m, &grpc.GenericServerStream[WatchScanStatusRequest, WatchScanStatusResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ScanService_WatchScanStatusServer = grpc.ServerStreamingServer[WatchScanStatusResponse]

// ScanService_ServiceDesc is the grpc.ServiceDesc for ScanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aegis.v2.ScanService",
	HandlerType: (*ScanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartScan",
			Handler:    _ScanService_StartScan_Handler,
		},
		{
			MethodName: "GetScanStatus",
			Handler:    _ScanService_GetScanStatus_Handler,
		},
		{
			MethodName: "ListScans",
			Handler:    _ScanService_ListScans_Handler,
		},
		{
			MethodName: "GetScanReport",
			Handler:    _ScanService_GetScanReport_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchScanStatus",
			Handler:       _ScanService_WatchScanStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "aegis/v2/scan.proto",
}
