// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aegis/v1/scan.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetImage   string                 `protobuf:"bytes,1,opt,name=target_image,json=targetImage,proto3" json:"target_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_aegis_v1_scan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_scan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_scan_proto_rawDescGZIP(), []int{0}
}

func (x *ScanRequest) GetTargetImage() string {
	if x != nil {
		return x.TargetImage
	}
	return ""
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_aegis_v1_scan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_scan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_scan_proto_rawDescGZIP(), []int{1}
}

func (x *ScanResponse) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *ScanResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScanResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

type GetScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScanRequest) Reset() {
	*x = GetScanRequest{}
	mi := &file_aegis_v1_scan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScanRequest) ProtoMessage() {}

func (x *GetScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_scan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScanRequest.ProtoReflect.Descriptor instead.
func (*GetScanRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_scan_proto_rawDescGZIP(), []int{2}
}

func (x *GetScanRequest) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

type ScanStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanStatusResponse) Reset() {
	*x = ScanStatusResponse{}
	mi := &file_aegis_v1_scan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanStatusResponse) ProtoMessage() {}

func (x *ScanStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_scan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanStatusResponse.ProtoReflect.Descriptor instead.
func (*ScanStatusResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_scan_proto_rawDescGZIP(), []int{3}
}

func (x *ScanStatusResponse) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *ScanStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScanStatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ScanStatusResponse) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

var File_aegis_v1_scan_proto protoreflect.FileDescriptor

const file_aegis_v1_scan_proto_rawDesc = "" +
	"\n" +
	"\x13aegis/v1/scan.proto\x12\baegis.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"0\n" +
	"\vScanRequest\x12!\n" +
	"\ftarget_image\x18\x01 \x01(\tR\vtargetImage\"z\n" +
	"\fScanResponse\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\")\n" +
	"\x0eGetScanRequest\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\"\xbf\x01\n" +
	"\x12ScanStatusResponse\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt2\x92\x01\n" +
	"\vScanService\x12:\n" +
	"\tStartScan\x12\x15.aegis.v1.ScanRequest\x1a\x16.aegis.v1.ScanResponse\x12G\n" +
	"\rGetScanStatus\x12\x18.aegis.v1.GetScanRequest\x1a\x1c.aegis.v1.ScanStatusResponseB;Z9github.com/Aegis-AI-Organizations/aegis-ai-proto/aegis/v1b\x06proto3"

var (
	file_aegis_v1_scan_proto_rawDescOnce sync.Once
	file_aegis_v1_scan_proto_rawDescData []byte
)

func file_aegis_v1_scan_proto_rawDescGZIP() []byte {
	file_aegis_v1_scan_proto_rawDescOnce.Do(func() {
		file_aegis_v1_scan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aegis_v1_scan_proto_rawDesc), len(file_aegis_v1_scan_proto_rawDesc)))
	})
	return file_aegis_v1_scan_proto_rawDescData
}

var file_aegis_v1_scan_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_aegis_v1_scan_proto_goTypes = []any{
	(*ScanRequest)(nil),           // 0: aegis.v1.ScanRequest
	(*ScanResponse)(nil),          // 1: aegis.v1.ScanResponse
	(*GetScanRequest)(nil),        // 2: aegis.v1.GetScanRequest
	(*ScanStatusResponse)(nil),    // 3: aegis.v1.ScanStatusResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_aegis_v1_scan_proto_depIdxs = []int32{
	4, // 0: aegis.v1.ScanResponse.started_at:type_name -> google.protobuf.Timestamp
	4, // 1: aegis.v1.ScanStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	4, // 2: aegis.v1.ScanStatusResponse.completed_at:type_name -> google.protobuf.Timestamp
	0, // 3: aegis.v1.ScanService.StartScan:input_type -> aegis.v1.ScanRequest
	2, // 4: aegis.v1.ScanService.GetScanStatus:input_type -> aegis.v1.GetScanRequest
	1, // 5: aegis.v1.ScanService.StartScan:output_type -> aegis.v1.ScanResponse
	3, // 6: aegis.v1.ScanService.GetScanStatus:output_type -> aegis.v1.ScanStatusResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_aegis_v1_scan_proto_init() }
func file_aegis_v1_scan_proto_init() {
	if File_aegis_v1_scan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aegis_v1_scan_proto_rawDesc), len(file_aegis_v1_scan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aegis_v1_scan_proto_goTypes,
		DependencyIndexes: file_aegis_v1_scan_proto_depIdxs,
		MessageInfos:      file_aegis_v1_scan_proto_msgTypes,
	}.Build()
	File_aegis_v1_scan_proto = out.File
	file_aegis_v1_scan_proto_goTypes = nil
	file_aegis_v1_scan_proto_depIdxs = nil
}
