// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aegis/v1/scan.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetImage   string                 `protobuf:"bytes,1,opt,name=target_image,json=targetImage,proto3" json:"target_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartScanRequest) Reset() {
	*x = StartScanRequest{}
	mi := &file_aegis_v1_scan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartScanRequest) ProtoMessage() {}

func (x *StartScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_scan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartScanRequest.ProtoReflect.Descriptor instead.
func (*StartScanRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_scan_proto_rawDescGZIP(), []int{0}
}

func (x *StartScanRequest) GetTargetImage() string {
	if x != nil {
		return x.TargetImage
	}
	return ""
}

type StartScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartScanResponse) Reset() {
	*x = StartScanResponse{}
	mi := &file_aegis_v1_scan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartScanResponse) ProtoMessage() {}

func (x *StartScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_scan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartScanResponse.ProtoReflect.Descriptor instead.
func (*StartScanResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_scan_proto_rawDescGZIP(), []int{1}
}

func (x *StartScanResponse) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *StartScanResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StartScanResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

type GetScanStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScanStatusRequest) Reset() {
	*x = GetScanStatusRequest{}
	mi := &file_aegis_v1_scan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScanStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScanStatusRequest) ProtoMessage() {}

func (x *GetScanStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_scan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScanStatusRequest.ProtoReflect.Descriptor instead.
func (*GetScanStatusRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_scan_proto_rawDescGZIP(), []int{2}
}

func (x *GetScanStatusRequest) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

type GetScanStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScanStatusResponse) Reset() {
	*x = GetScanStatusResponse{}
	mi := &file_aegis_v1_scan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScanStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScanStatusResponse) ProtoMessage() {}

func (x *GetScanStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_scan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScanStatusResponse.ProtoReflect.Descriptor instead.
func (*GetScanStatusResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_scan_proto_rawDescGZIP(), []int{3}
}

func (x *GetScanStatusResponse) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *GetScanStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetScanStatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *GetScanStatusResponse) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

var File_aegis_v1_scan_proto protoreflect.FileDescriptor

const file_aegis_v1_scan_proto_rawDesc = "" +
	"\n" +
	"\x13aegis/v1/scan.proto\x12\baegis.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"5\n" +
	"\x10StartScanRequest\x12!\n" +
	"\ftarget_image\x18\x01 \x01(\tR\vtargetImage\"\x7f\n" +
	"\x11StartScanResponse\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"/\n" +
	"\x14GetScanStatusRequest\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\"\xc2\x01\n" +
	"\x15GetScanStatusResponse\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt2\xa5\x01\n" +
	"\vScanService\x12D\n" +
	"\tStartScan\x12\x1a.aegis.v1.StartScanRequest\x1a\x1b.aegis.v1.StartScanResponse\x12P\n" +
	"\rGetScanStatus\x12\x1e.aegis.v1.GetScanStatusRequest\x1a\x1f.aegis.v1.GetScanStatusResponseB;Z9github.com/Aegis-AI-Organizations/aegis-ai-proto/aegis/v1b\x06proto3"

var (
	file_aegis_v1_scan_proto_rawDescOnce sync.Once
	file_aegis_v1_scan_proto_rawDescData []byte
)

func file_aegis_v1_scan_proto_rawDescGZIP() []byte {
	file_aegis_v1_scan_proto_rawDescOnce.Do(func() {
		file_aegis_v1_scan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aegis_v1_scan_proto_rawDesc), len(file_aegis_v1_scan_proto_rawDesc)))
	})
	return file_aegis_v1_scan_proto_rawDescData
}

var file_aegis_v1_scan_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_aegis_v1_scan_proto_goTypes = []any{
	(*StartScanRequest)(nil),      // 0: aegis.v1.StartScanRequest
	(*StartScanResponse)(nil),     // 1: aegis.v1.StartScanResponse
	(*GetScanStatusRequest)(nil),  // 2: aegis.v1.GetScanStatusRequest
	(*GetScanStatusResponse)(nil), // 3: aegis.v1.GetScanStatusResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_aegis_v1_scan_proto_depIdxs = []int32{
	4, // 0: aegis.v1.StartScanResponse.started_at:type_name -> google.protobuf.Timestamp
	4, // 1: aegis.v1.GetScanStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	4, // 2: aegis.v1.GetScanStatusResponse.completed_at:type_name -> google.protobuf.Timestamp
	0, // 3: aegis.v1.ScanService.StartScan:input_type -> aegis.v1.StartScanRequest
	2, // 4: aegis.v1.ScanService.GetScanStatus:input_type -> aegis.v1.GetScanStatusRequest
	1, // 5: aegis.v1.ScanService.StartScan:output_type -> aegis.v1.StartScanResponse
	3, // 6: aegis.v1.ScanService.GetScanStatus:output_type -> aegis.v1.GetScanStatusResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_aegis_v1_scan_proto_init() }
func file_aegis_v1_scan_proto_init() {
	if File_aegis_v1_scan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aegis_v1_scan_proto_rawDesc), len(file_aegis_v1_scan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aegis_v1_scan_proto_goTypes,
		DependencyIndexes: file_aegis_v1_scan_proto_depIdxs,
		MessageInfos:      file_aegis_v1_scan_proto_msgTypes,
	}.Build()
	File_aegis_v1_scan_proto = out.File
	file_aegis_v1_scan_proto_goTypes = nil
	file_aegis_v1_scan_proto_depIdxs = nil
}
